# Generated by Django 4.1 on 2022-08-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='subject',
        ),
    ]
